//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Web.Resources.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adult.
        /// </summary>
        public static string Adult {
            get {
                return ResourceManager.GetString("Adult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrival date.
        /// </summary>
        public static string ArrivalDate {
            get {
                return ResourceManager.GetString("ArrivalDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average size.
        /// </summary>
        public static string AverageSize {
            get {
                return ResourceManager.GetString("AverageSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baby.
        /// </summary>
        public static string Baby {
            get {
                return ResourceManager.GetString("Baby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Best price guaranteed.
        /// </summary>
        public static string BestPrice {
            get {
                return ResourceManager.GetString("BestPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agency with no middlemen, guaranteed price parity..
        /// </summary>
        public static string BestPriceDescription {
            get {
                return ResourceManager.GetString("BestPriceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guaranteed departure booking.
        /// </summary>
        public static string BookingNow {
            get {
                return ResourceManager.GetString("BookingNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Child.
        /// </summary>
        public static string Child {
            get {
                return ResourceManager.GetString("Child", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The leading specialist in high-quality travel to Asia..
        /// </summary>
        public static string ChuyenGiaDuLich {
            get {
                return ResourceManager.GetString("ChuyenGiaDuLich", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        public static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days.
        /// </summary>
        public static string Days {
            get {
                return ResourceManager.GetString("Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departure city.
        /// </summary>
        public static string DepartureCity {
            get {
                return ResourceManager.GetString("DepartureCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination.
        /// </summary>
        public static string Destination {
            get {
                return ResourceManager.GetString("Destination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail.
        /// </summary>
        public static string Detail {
            get {
                return ResourceManager.GetString("Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        public static string Duration {
            get {
                return ResourceManager.GetString("Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        public static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        public static string Group {
            get {
                return ResourceManager.GetString("Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guide&apos;s language.
        /// </summary>
        public static string GuideLang {
            get {
                return ResourceManager.GetString("GuideLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home page.
        /// </summary>
        public static string HomePage {
            get {
                return ResourceManager.GetString("HomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotel.
        /// </summary>
        public static string Hotel {
            get {
                return ResourceManager.GetString("Hotel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotel category.
        /// </summary>
        public static string HotelCategory {
            get {
                return ResourceManager.GetString("HotelCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Itinerary.
        /// </summary>
        public static string Itinerary {
            get {
                return ResourceManager.GetString("Itinerary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Journey.
        /// </summary>
        public static string Journey {
            get {
                return ResourceManager.GetString("Journey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferred language.
        /// </summary>
        public static string NgonNguUuTien {
            get {
                return ResourceManager.GetString("NgonNguUuTien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nigths.
        /// </summary>
        public static string Nigths {
            get {
                return ResourceManager.GetString("Nigths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please complete the details requested below, and we will contact you within 24 to 48 hours. Fields marked with an asterisk (*) are mandatory. Please note that intercontinental flights are not included and are quoted separately..
        /// </summary>
        public static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes and preferences.
        /// </summary>
        public static string NotesAnd {
            get {
                return ResourceManager.GetString("NotesAnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passenger.
        /// </summary>
        public static string Passenger {
            get {
                return ResourceManager.GetString("Passenger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single supplement.
        /// </summary>
        public static string PhuPhi {
            get {
                return ResourceManager.GetString("PhuPhi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tell us about your ideal trip: hotel category, dining preferences, interests, travel companions, and preferences regarding flights and attractions. The more details you provide, the better we can personalize it for you..
        /// </summary>
        public static string PlaceNotes {
            get {
                return ResourceManager.GetString("PlaceNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the country code..
        /// </summary>
        public static string PlaceTel {
            get {
                return ResourceManager.GetString("PlaceTel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private.
        /// </summary>
        public static string Private {
            get {
                return ResourceManager.GetString("Private", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of the package.
        /// </summary>
        public static string ProductCode {
            get {
                return ResourceManager.GetString("ProductCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See more.
        /// </summary>
        public static string SeeMore {
            get {
                return ResourceManager.GetString("SeeMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the desired date.
        /// </summary>
        public static string SelectDate {
            get {
                return ResourceManager.GetString("SelectDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asian travel expert.
        /// </summary>
        public static string Slogan {
            get {
                return ResourceManager.GetString("Slogan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instant support.
        /// </summary>
        public static string SpeedSupport {
            get {
                return ResourceManager.GetString("SpeedSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our local experts are available to assist you 24/7..
        /// </summary>
        public static string SpeedSupportDesc {
            get {
                return ResourceManager.GetString("SpeedSupportDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting point.
        /// </summary>
        public static string StartingPoint {
            get {
                return ResourceManager.GetString("StartingPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group and private tours.
        /// </summary>
        public static string StyleTour {
            get {
                return ResourceManager.GetString("StyleTour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High-quality group tours in Spanish across Asia and personalized trips..
        /// </summary>
        public static string StyleTourDesc {
            get {
                return ResourceManager.GetString("StyleTourDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks for the request!.
        /// </summary>
        public static string ThankYouRequest {
            get {
                return ResourceManager.GetString("ThankYouRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More itineraries.
        /// </summary>
        public static string ThemLichTrinh {
            get {
                return ResourceManager.GetString("ThemLichTrinh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimated total.
        /// </summary>
        public static string TongUocTinh {
            get {
                return ResourceManager.GetString("TongUocTinh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tour type.
        /// </summary>
        public static string TourType {
            get {
                return ResourceManager.GetString("TourType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimated per person.
        /// </summary>
        public static string UocTinhTrenNguoi {
            get {
                return ResourceManager.GetString("UocTinhTrenNguoi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Why Paso Sea Tour?.
        /// </summary>
        public static string WhyChooses {
            get {
                return ResourceManager.GetString("WhyChooses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request a quote.
        /// </summary>
        public static string YCBaoGia {
            get {
                return ResourceManager.GetString("YCBaoGia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enjoy the ultimate vacation..
        /// </summary>
        public static string YenTamDesc {
            get {
                return ResourceManager.GetString("YenTamDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Travel with peace of mind..
        /// </summary>
        public static string YenTamDuLich {
            get {
                return ResourceManager.GetString("YenTamDuLich", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request a quote.
        /// </summary>
        public static string YeuCauBaoGia {
            get {
                return ResourceManager.GetString("YeuCauBaoGia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request a consultation.
        /// </summary>
        public static string YeuCauTuVan {
            get {
                return ResourceManager.GetString("YeuCauTuVan", resourceCulture);
            }
        }
    }
}
