//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Web.Resources.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Best price guaranteed.
        /// </summary>
        public static string BestPrice {
            get {
                return ResourceManager.GetString("BestPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agency with no middlemen, guaranteed price parity..
        /// </summary>
        public static string BestPriceDescription {
            get {
                return ResourceManager.GetString("BestPriceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The leading specialist in high-quality travel to Asia..
        /// </summary>
        public static string ChuyenGiaDuLich {
            get {
                return ResourceManager.GetString("ChuyenGiaDuLich", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days.
        /// </summary>
        public static string Days {
            get {
                return ResourceManager.GetString("Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination.
        /// </summary>
        public static string Destination {
            get {
                return ResourceManager.GetString("Destination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail.
        /// </summary>
        public static string Detail {
            get {
                return ResourceManager.GetString("Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nigths.
        /// </summary>
        public static string Nigths {
            get {
                return ResourceManager.GetString("Nigths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting price.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See more.
        /// </summary>
        public static string SeeMore {
            get {
                return ResourceManager.GetString("SeeMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asian travel expert.
        /// </summary>
        public static string Slogan {
            get {
                return ResourceManager.GetString("Slogan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instant support.
        /// </summary>
        public static string SpeedSupport {
            get {
                return ResourceManager.GetString("SpeedSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our local experts are available to assist you 24/7..
        /// </summary>
        public static string SpeedSupportDesc {
            get {
                return ResourceManager.GetString("SpeedSupportDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group and private tours.
        /// </summary>
        public static string StyleTour {
            get {
                return ResourceManager.GetString("StyleTour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High-quality group tours in Spanish across Asia and personalized trips..
        /// </summary>
        public static string StyleTourDesc {
            get {
                return ResourceManager.GetString("StyleTourDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Why Paso Sea Tour?.
        /// </summary>
        public static string WhyChooses {
            get {
                return ResourceManager.GetString("WhyChooses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enjoy the ultimate vacation..
        /// </summary>
        public static string YenTamDesc {
            get {
                return ResourceManager.GetString("YenTamDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Travel with peace of mind..
        /// </summary>
        public static string YenTamDuLich {
            get {
                return ResourceManager.GetString("YenTamDuLich", resourceCulture);
            }
        }
    }
}
