//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenuTran
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string LinkSeo { get; set; }
        public int MenuID { get; set; }
        public int ParentID { get; set; }
        public int Level { get; set; }
        public int Ordering { get; set; }
        public string LangCode { get; set; }
    }
}
