//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class WebDuLichEntities : DbContext
    {
        public WebDuLichEntities()
            : base("name=WebDuLichEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdminMenu> AdminMenus { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Contact> Contacts { get; set; }
        public virtual DbSet<Header> Headers { get; set; }
        public virtual DbSet<News> News { get; set; }
        public virtual DbSet<Slider> Sliders { get; set; }
        public virtual DbSet<tbl_GroupUser> tbl_GroupUser { get; set; }
        public virtual DbSet<tbl_Login> tbl_Login { get; set; }
        public virtual DbSet<tbl_PageElement> tbl_PageElement { get; set; }
        public virtual DbSet<UserAdmin> UserAdmins { get; set; }
        public virtual DbSet<Topic> Topics { get; set; }
        public virtual DbSet<UserTran> UserTrans { get; set; }
        public virtual DbSet<tbl_User> tbl_User { get; set; }
        public virtual DbSet<MenuHome> MenuHomes { get; set; }
        public virtual DbSet<tbl_Languages> tbl_Languages { get; set; }
        public virtual DbSet<Theme> Themes { get; set; }
        public virtual DbSet<About> Abouts { get; set; }
        public virtual DbSet<TopicTran> TopicTrans { get; set; }
        public virtual DbSet<Menu> Menus { get; set; }
        public virtual DbSet<MenuTran> MenuTrans { get; set; }
        public virtual DbSet<BannerTran> BannerTrans { get; set; }
        public virtual DbSet<Banner> Banners { get; set; }
        public virtual DbSet<ProductTran> ProductTrans { get; set; }
        public virtual DbSet<Introduction> Introductions { get; set; }
        public virtual DbSet<IntroductionTran> IntroductionTrans { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<CountryTran> CountryTrans { get; set; }
        public virtual DbSet<Location> Locations { get; set; }
        public virtual DbSet<LocationTran> LocationTrans { get; set; }
        public virtual DbSet<Hotel> Hotels { get; set; }
        public virtual DbSet<HotelTran> HotelTrans { get; set; }
        public virtual DbSet<Product> Products { get; set; }
    
        public virtual int Sp_Category_Update(Nullable<int> iD, string name, string linkSeo, Nullable<int> parentID, Nullable<int> ordering, Nullable<int> type, Nullable<int> level, string icon, Nullable<int> position, Nullable<bool> isSearch, string pathway)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            var linkSeoParameter = linkSeo != null ?
                new ObjectParameter("LinkSeo", linkSeo) :
                new ObjectParameter("LinkSeo", typeof(string));
    
            var parentIDParameter = parentID.HasValue ?
                new ObjectParameter("ParentID", parentID) :
                new ObjectParameter("ParentID", typeof(int));
    
            var orderingParameter = ordering.HasValue ?
                new ObjectParameter("Ordering", ordering) :
                new ObjectParameter("Ordering", typeof(int));
    
            var typeParameter = type.HasValue ?
                new ObjectParameter("Type", type) :
                new ObjectParameter("Type", typeof(int));
    
            var levelParameter = level.HasValue ?
                new ObjectParameter("Level", level) :
                new ObjectParameter("Level", typeof(int));
    
            var iconParameter = icon != null ?
                new ObjectParameter("Icon", icon) :
                new ObjectParameter("Icon", typeof(string));
    
            var positionParameter = position.HasValue ?
                new ObjectParameter("Position", position) :
                new ObjectParameter("Position", typeof(int));
    
            var isSearchParameter = isSearch.HasValue ?
                new ObjectParameter("IsSearch", isSearch) :
                new ObjectParameter("IsSearch", typeof(bool));
    
            var pathwayParameter = pathway != null ?
                new ObjectParameter("Pathway", pathway) :
                new ObjectParameter("Pathway", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_Category_Update", iDParameter, nameParameter, linkSeoParameter, parentIDParameter, orderingParameter, typeParameter, levelParameter, iconParameter, positionParameter, isSearchParameter, pathwayParameter);
        }
    
        public virtual ObjectResult<Sp_News_GetByLinkSeo_Result> Sp_News_GetByLinkSeo(string linkSeo)
        {
            var linkSeoParameter = linkSeo != null ?
                new ObjectParameter("LinkSeo", linkSeo) :
                new ObjectParameter("LinkSeo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_News_GetByLinkSeo_Result>("Sp_News_GetByLinkSeo", linkSeoParameter);
        }
    
        public virtual ObjectResult<Sp_News_GetByTitle_Result> Sp_News_GetByTitle(string metaTitle)
        {
            var metaTitleParameter = metaTitle != null ?
                new ObjectParameter("MetaTitle", metaTitle) :
                new ObjectParameter("MetaTitle", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_News_GetByTitle_Result>("Sp_News_GetByTitle", metaTitleParameter);
        }
    
        public virtual int Sp_News_Insert(Nullable<int> categoryId, string metaTitle, string linkSeo, string image, string description, Nullable<int> createdBy, string contents, Nullable<int> status, string tags, Nullable<int> type)
        {
            var categoryIdParameter = categoryId.HasValue ?
                new ObjectParameter("CategoryId", categoryId) :
                new ObjectParameter("CategoryId", typeof(int));
    
            var metaTitleParameter = metaTitle != null ?
                new ObjectParameter("MetaTitle", metaTitle) :
                new ObjectParameter("MetaTitle", typeof(string));
    
            var linkSeoParameter = linkSeo != null ?
                new ObjectParameter("LinkSeo", linkSeo) :
                new ObjectParameter("LinkSeo", typeof(string));
    
            var imageParameter = image != null ?
                new ObjectParameter("Image", image) :
                new ObjectParameter("Image", typeof(string));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("Description", description) :
                new ObjectParameter("Description", typeof(string));
    
            var createdByParameter = createdBy.HasValue ?
                new ObjectParameter("CreatedBy", createdBy) :
                new ObjectParameter("CreatedBy", typeof(int));
    
            var contentsParameter = contents != null ?
                new ObjectParameter("Contents", contents) :
                new ObjectParameter("Contents", typeof(string));
    
            var statusParameter = status.HasValue ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(int));
    
            var tagsParameter = tags != null ?
                new ObjectParameter("Tags", tags) :
                new ObjectParameter("Tags", typeof(string));
    
            var typeParameter = type.HasValue ?
                new ObjectParameter("Type", type) :
                new ObjectParameter("Type", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_News_Insert", categoryIdParameter, metaTitleParameter, linkSeoParameter, imageParameter, descriptionParameter, createdByParameter, contentsParameter, statusParameter, tagsParameter, typeParameter);
        }
    
        public virtual int Sp_News_Update(Nullable<int> iD, Nullable<int> categoryId, string metaTitle, string linkSeo, string image, string description, Nullable<int> modifiedBy, string contents, Nullable<int> status, string tags)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            var categoryIdParameter = categoryId.HasValue ?
                new ObjectParameter("CategoryId", categoryId) :
                new ObjectParameter("CategoryId", typeof(int));
    
            var metaTitleParameter = metaTitle != null ?
                new ObjectParameter("MetaTitle", metaTitle) :
                new ObjectParameter("MetaTitle", typeof(string));
    
            var linkSeoParameter = linkSeo != null ?
                new ObjectParameter("LinkSeo", linkSeo) :
                new ObjectParameter("LinkSeo", typeof(string));
    
            var imageParameter = image != null ?
                new ObjectParameter("Image", image) :
                new ObjectParameter("Image", typeof(string));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("Description", description) :
                new ObjectParameter("Description", typeof(string));
    
            var modifiedByParameter = modifiedBy.HasValue ?
                new ObjectParameter("ModifiedBy", modifiedBy) :
                new ObjectParameter("ModifiedBy", typeof(int));
    
            var contentsParameter = contents != null ?
                new ObjectParameter("Contents", contents) :
                new ObjectParameter("Contents", typeof(string));
    
            var statusParameter = status.HasValue ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(int));
    
            var tagsParameter = tags != null ?
                new ObjectParameter("Tags", tags) :
                new ObjectParameter("Tags", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_News_Update", iDParameter, categoryIdParameter, metaTitleParameter, linkSeoParameter, imageParameter, descriptionParameter, modifiedByParameter, contentsParameter, statusParameter, tagsParameter);
        }
    }
}
