//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Package_Price
    {
        public int ID { get; set; }
        public Nullable<int> Pax_From { get; set; }
        public Nullable<int> Pax_To { get; set; }
        public Nullable<double> Price { get; set; }
        public int PackageID { get; set; }
        public int ProductID { get; set; }
    }
}
