//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int ID { get; set; }
        public string ProductCode { get; set; }
        public string Image { get; set; }
        public bool Active { get; set; }
        public int MenuID { get; set; }
        public int Type { get; set; }
        public Nullable<double> Price { get; set; }
        public string Size { get; set; }
        public Nullable<int> DayNumber { get; set; }
        public string CountryID { get; set; }
        public string LocationID { get; set; }
        public string HotelID { get; set; }
        public Nullable<int> NumberStar { get; set; }
        public System.DateTime CreatedDate { get; set; }
    }
}
