//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductTran
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public string LinkSeo { get; set; }
        public string Description { get; set; }
        public string Contents { get; set; }
        public string LangCode { get; set; }
        public int ProductID { get; set; }
    }
}
