//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SentMail
    {
        public int ID { get; set; }
        public string MailTo { get; set; }
        public string MailCC { get; set; }
        public string Subject { get; set; }
        public string Contents { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> RetryCount { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> SentDate { get; set; }
        public Nullable<int> BookingID { get; set; }
    }
}
