//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_User
    {
        public int ID { get; set; }
        public string Email { get; set; }
        public string FullName { get; set; }
        public string Gender { get; set; }
        public string Photo { get; set; }
        public bool Active { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string Phone { get; set; }
        public Nullable<int> CountryID { get; set; }
        public Nullable<int> LangID { get; set; }
    }
}
